services:

  kache:
    image: kacheio/kache:latest
    container_name: kache
    command:
      - "-config.file=/etc/kache/kache.sample.yml"
    ports:
      - "80:80"
      - "3129:3129"
      - "6067:6067"
    volumes:
      - "./../kache.sample.yml:/etc/kache/kache.sample.yml"

  redis:
    image: "redis:alpine"
