apiVersion: v1
kind: ConfigMap
metadata:
  name: kache-config
data:
  config.yml: |-
    listeners:
      web1:
        addr: :80
      web2:
        addr: :3128
    upstreams:
      - name: service1
        addr: "http://localhost:8000"
        path: "/service1"
      - name: service
        addr: "http://example.com"
        path: "/"
    api:
      port: 6067
      debug: true
    logging:
      level: debug
    provider:
      layered: true
      backend: redis
      redis:
        endpoint: "redis-master:6379"
        username:
        password:
        db:
        max_item_size: 10000000
        max_queue_concurrency: 56
        max_queue_buffer_size: 24000
      inmemory:
        max_size:
        max_item_size:
    cluster:
      discovery: kubernetes
      namespace: default
      service: kache-service
