---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kache
  template:
    metadata:
      labels:
        app: kache
    spec:
      containers:
        - name: kache
          # Use 'latest' for latest release, or 'main' for live at head.
          image: kacheio/kache:latest
          imagePullPolicy: Always
          # Uncomment to use local image (mainly used for testing):
          # image: kacheio/kluster
          # imagePullPolicy: Never
          args:
            - "-config.file=/etc/kache/config.yml"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /etc/kache
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3128
              name: web
            - containerPort: 6067
              name: api
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: config
          configMap:
            name: kache-config

---
apiVersion: v1
kind: Service
metadata:
  name: kache-service
  labels:
    app: kache
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: http
    - name: "web"
      port: 3128
      targetPort: web
    - name: "api"
      port: 6067
      targetPort: api
  selector:
    app: kache
    
# Start/Restart pods:
# kubectl scale deploy kache --replicas=[0|n]
