apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kache-service
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"]
